type Query{
	users(userId: String, token: String!): [User!]!
}

type User{
	userId: ID!
	username: String!
	password: String!
	contact: String!
	email: String!
}


type Mutation{
	createUser(
		username: String!
		password: String!
		contact: String!
		email: String!
	): Response!

	loginUser(
		username: String!
		password: String!
	): Response!
}

type Response{
	status: String!
	message: String!
	token: String!
}